Prefer `static` default interface methods
Fixes a nasty regression caused by method erasure in release-mode AOT
builds, i.e.,

  > System.NotSupportedException: The body of this instance method was
  > removed by the AOT compiler. This can happen if the owning type was
  > not seen as allocated by the AOT compiler.
  >
  >  at Npp.DotNet.Plugin.Demo.Main.GetFuncsArray(IntPtr) + 0x35
  > ...